---
- hosts: nodes
  become: true
  tasks:
          - name: download ambari repo file
            get_url:
                    url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.0.0/ambari.repo
                    dest: /etc/yum.repos.d

          - name: install the latest version of ambari agent
            yum:
                    name: ambari-agent
                    state: latest

          - name: remove ambari server
            yum:
                    name: ambari-server
                    state: absent

          - name: ansible replace hostname to lxmaster
            replace:
                    path: /etc/ambari-agent/conf/ambari-agent.ini
                    regexp: 'localhost'
                    replace: 'lxmaster'

          - name: copy hosts file to all nodes
            copy:
                    src: /home/lcox/work/ansible/playbooks/hosts
                    dest: /etc/hosts

          - name: start service ambari-agent on all nodes
            service:
                    name: ambari-agent
                    state: started
